### ISSUE TITLE
Error on filter page: Data smaple is too short

### ISSUE THREAD

**Issue by Karlo-Emilo** [microbit-foundation/cctd-ml-machine#457]
I get this error when I go to the filter page while having an input micro:bit connected. 

![image](https://github.com/microbit-foundation/cctd-ml-machine/assets/12435057/5f89d6f3-9d8a-4c5d-ac9c-aef67a2a8b21)

**Comment by r59q** [comment]
This happened, because the filters page only computed the graphs based on a single point. This is impossible with the peaks filter, as it must have a history of points to compute the number of peaks.

This is addressed by changing the computation to take into account the same duration as gesture recordings are
