### ISSUE TITLE
(Main) Error in PeaksFilter 

### ISSUE THREAD

**Issue by Karlo-Emilo** [microbit-foundation/cctd-ml-machine#499]
Error appears on Main branch.

Reproduce:
 1. Add data samples on data page
 2. Go to training page

```

PeaksFilter.ts:30 Uncaught Error: data sample is too short
    at PeaksFilter.filter (PeaksFilter.ts:30:13)
    at Filters.ts:22:21
    at Array.map (<anonymous>)
    at Filters.compute (Filters.ts:21:30)
    at getLiveFilteredData (KNNModelGraphController.ts:198:31)
    at KNNModelGraphController.onUpdate (KNNModelGraphController.ts:208:22)
    at KNNModelGraphController.ts:71:12
```

**Comment by r59q** [comment]
I'm not sure I would call it a bug, as it is the intended behavior. The issue arises due to the engine always being started, and thus it tries to predict on an empty dataset, which the peaks filter cannot handle.

The error goes away when the microbit has been producing inputs for a few seconds.

I'm not entirely sure how to handle the error at the moment, as simply silencing it could be problematic when debugging.

The elegant solution would be to ensure the engine doesn't attempt to predict when the live data store is empty, but the required number of elements is dependent on the specific filters. 

We might implement a getMinElements() method in the filter and use that to tell the engine how many is required to perform a prediction

**Comment by Karlo-Emilo** [comment]
I see. It may not be so urgent to implement a more elegant solution.

**Comment by r59q** [comment]
Added check to ensure the minimum number of values required are present
